<style>

.overflow{
position: fixed;
width: 100%;
height: 100%;
overflow: hidden;
right: 0;
bottom: 0;
display: block;
/*background: #cbd8d77d;*/
background: #446303de;

z-index: 99999999999;
}


#preload-status {
position: absolute;
width: 200px;
height: 200px;
margin: auto;
padding: 0;
top: 0;
right: 0;
bottom: 0;
left: 0;
display: block;
/*background: #000 url(/Web/img/loader.gif) no-repeat center center;*/
}

/*!
* LOADER FOR LOGIN CSS END
*/
</style>


<style type="text/css">
@keyframes ldio-8rltnd7anu2 {
    0% { transform: rotate(0deg) }
   50% { transform: rotate(22.5deg) }
  100% { transform: rotate(45deg) }
}
.ldio-8rltnd7anu2 > div {
  transform-origin: 100px 100px;
  animation: ldio-8rltnd7anu2 0.2s infinite linear;
}
.ldio-8rltnd7anu2 > div div {
    position: absolute;
    width: 16px;
    height: 144px;
    background: #8ec31ffc;
    left: 100px;
    top: 100px;
    transform: translate(-50%,-50%);
}
.ldio-8rltnd7anu2 > div div:nth-child(1) {
    width: 120px;
    height: 120px;
    border-radius: 50%;
}
.ldio-8rltnd7anu2 > div div:nth-child(6) {
    width: 80px;
    height: 80px;
    background: #446303de;
    border-radius: 50%;
}.ldio-8rltnd7anu2 > div div:nth-child(3) {
  transform: translate(-50%,-50%) rotate(45deg)
}.ldio-8rltnd7anu2 > div div:nth-child(4) {
  transform: translate(-50%,-50%) rotate(90deg)
}.ldio-8rltnd7anu2 > div div:nth-child(5) {
  transform: translate(-50%,-50%) rotate(135deg)
}
.loadingio-spinner-gear-e2se2hux5mo {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-8rltnd7anu2 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-8rltnd7anu2 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
<div class="overflow" >
  <div id="preload-status">
    
      
<div class="loadingio-spinner-gear-e2se2hux5mo"><div class="ldio-8rltnd7anu2">
<div><div></div><div></div><div></div><div></div><div></div><div></div></div>
</div></div>

			<!-- <img src="/Web/images/loadertext.gif"> -->
     </div>
</div>





