<style>

.overflow{
position: absolute;
width: 100%;
height: 100%;
overflow: hidden;
right: 0;
bottom: 0;
/*background: #cbd8d77d;*/
background: #cbd8d77d;
display: block;
z-index: 99999999999;
}


#preload-status {
position: absolute;
width: 200px;
height: 200px;
margin: auto;
padding: 0;
top: 0;
right: 0;
bottom: 0;
left: 0;
display: block;
/*background: #000 url(/Web/img/loader.gif) no-repeat center center;*/
}

/*!
* LOADER FOR LOGIN CSS END
*/
</style>


<style type="text/css">

@keyframes ldio-z271tlmiuo {
  0% {
    top: 72px;
    left: 72px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 6px;
    left: 6px;
    width: 132px;
    height: 132px;
    opacity: 0;
  }
}

.ldio-z271tlmiuo div {
  position: absolute;
  border-width: 28px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-z271tlmiuo 2.9411764705882355s cubic-bezier(0,0.2,0.8,1) infinite;
}

.ldio-z271tlmiuo div:nth-child(1) {
  border-color: #93dbe9
}

.ldio-z271tlmiuo div:nth-child(2) {
  border-color: #689cc5;
  animation-delay: -1.4705882352941178s;
}

.loadingio-spinner-ripple-c8yq7l515vj {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-z271tlmiuo {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-z271tlmiuo div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
<div class="overflow" >
  <div id="preload-status">
    
      
  			<div class="loadingio-spinner-ripple-c8yq7l515vj"><div class="ldio-z271tlmiuo">
			<div></div>
			<div></div>
			</div></div>

			<!-- <img src="/Web/images/loadertext.gif"> -->
     </div>
</div>