<style>

.overflow{
position: fixed;
width: 100%;
height: 100%;
overflow: hidden;
right: 0;
bottom: 0;
/*background: #cbd8d77d;*/
background: #cbd8d77d;
display: block;
z-index: 99999999999;
}


#preload-status {
position: absolute;
width: 200px;
height: 200px;
margin: auto;
padding: 0;
top: 0;
right: 0;
bottom: 0;
left: 0;
display: block;
/*background: #000 url(/Web/img/loader.gif) no-repeat center center;*/
}

/*!
* LOADER FOR LOGIN CSS END
*/
</style>


<style type="text/css">
@keyframes ldio-gwdl1tu81lr {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-gwdl1tu81lr div {
  position: absolute;
  width: 177.75px;
  height: 177.75px;
  border: 2.37px solid #2c8615;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-gwdl1tu81lr div {
  animation: ldio-gwdl1tu81lr 1.5384615384615383s linear infinite;
  top: 118.5px;
  left: 118.5px
}
.loadingio-spinner-rolling-k12cph03t4s {
  width: 237px;
  height: 237px;
  display: inline-block;
  overflow: hidden;
  background: rgba(NaN, NaN, NaN, 0);
}
.ldio-gwdl1tu81lr {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-gwdl1tu81lr div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>

<div class="overflow" >
  <div id="preload-status">
    
      
  	<div class="loadingio-spinner-rolling-k12cph03t4s"><div class="ldio-gwdl1tu81lr">
<div></div>
</div></div>

			<!-- <img src="/Web/images/loadertext.gif"> -->
     </div>
</div>





